---
galaxy_info:
  role_name: wazuh_uninstall
  author: Tamir Suliman
  description: Stop services, remove packages, and purge data/config for a Wazuh component
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
